### ISSUE TITLE
Error displaying /history

### ISSUE THREAD

**Issue by dorian599** [adamcooke/staytus#213]
When the number of *ISSUES + MAINTENANCE* is greater than 25 and you try to access to */history* an error screen appears.

![screen shot 2018-01-31 at 9 03 45 pm](https://user-images.githubusercontent.com/3279245/35654157-848f3164-06ca-11e8-8a32-f8de28423525.png)

**Comment by ravloony** [comment]
I have this too. Here is a log from our instance:

```
==> /var/lib/staytus/log/puma.error.log <==
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04] Started GET "/history" for 81.16.159.162 at 2018-02-20 11:10:11 +0100
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04] Processing by PagesController#history as HTML
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   Site Load (0.8ms)  SELECT  `sites`.* FROM `sites` ORDER BY `sites`.`id` ASC LIMIT 1
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   Rendering content/themes/company/views/pages/history.html.erb within layouts/company
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   HistoryItem Load (1.0ms)  SELECT  `history_items`.* FROM `history_items` ORDER BY `history_items`.`date` DESC LIMIT 25 OFFSET 0
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   Maintenance Load (1.2ms)  SELECT `maintenances`.* FROM `maintenances` WHERE `maintenances`.`id` IN (20, 14, 16, 17, 10, 19, 18, 15, 9, 13, 12, 8, 11, 6, 3, 2, 7, 1, 5, 4)
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   Issue Load (0.8ms)  SELECT `issues`.* FROM `issues` WHERE `issues`.`id` IN (6, 5, 4, 3, 2)
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]    (0.9ms)  SELECT COUNT(*) FROM `history_items`
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   Rendered content/themes/company/views/pages/history.html.erb within layouts/company (61.6ms)
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04] Completed 500 Internal Server Error in 75ms (ActiveRecord: 4.8ms)
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04] ActionView::Template::Error (unable to convert unpermitted parameters to hash):
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     11:     <%= first_page_tag unless current_page.first? %>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     12:     <%= prev_page_tag unless current_page.first? %>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     13:     <% each_page do |page| -%>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     14:       <% if page.left_outer? || page.right_outer? || page.inside_window? -%>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     15:         <%= page_tag page %>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     16:       <% elsif !page.was_truncated? -%>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]     17:         <%= gap_tag %>
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04]   
[9c0c0987-85e0-40c6-ac74-34ffe90f2e04] app/controllers/application_controller.rb:22:in `set_time_zone'

```

**Comment by adamcooke** [comment]
Are you running the latest version of Staytus? This issue was fixed quite recently.

**Comment by martchoice** [comment]
I just did the updrade and unfortunately, I'm still having the issue. Tried both, public and admin pages.

Then, I tried to restart with procodile but I keep getting the error message.

Any idea?
